module.exports = {
  MAP_WIDTH: 3000,
  MAP_HEIGHT: 3000,

  PLAYER_RADIUS: 18,
  PLAYER_SPEED: 6.0,

  PICKUP_RADIUS: 14,
  PICKUP_COUNT: 60,

  ORBIT_RADIUS_BASE: 45,
  ORBIT_RADIUS_STEP: 18,
  ORBIT_ITEM_RADIUS: 11,
  ORBIT_SPEED: 0.2,

  TICK_RATE: 60,
  SCORE_PER_PICKUP: 10,
  SPAWN_PROTECTION_TICKS: 180,
};
